---
- name: custom-runtime-connector-apb playbook to test the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - /opt/ansible/vars/main.yml

  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  post_tasks:
  - name: Load default variables for testing
    include_vars: test.yml
  - name: Create project for namespace
    openshift_v1_project:
      name: '{{ namespace }}'
  - include_role:
      name: provision-crc-apb
  - include_role:
      name: test-provision-crc-apb
  - include_role:
      name: deprovision-crc-apb
  - include_role:
      name: test-deprovision-crc-apb